"""initial migration

Revision ID: 799b08179ad9
Revises: 
Create Date: 2026-09-28 03:40:25.877363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('input_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voting_criteria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('scoring_rules', sa.JSON(), nullable=True),
    sa.Column('ai_prompt_template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replayability', sa.JSON(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guest_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detection_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_detection_rating', ['detection_rating'], unique=False)
        batch_op.create_index('idx_users_guest_id', ['guest_id'], unique=False)

    op.create_table('challenge_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('challenge_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_constraints', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('leaderboard_snapshots',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('date', 'user_id')
    )
    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_leaderboard_date', ['date'], unique=False)

    op.create_table('prompt_audit',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenge_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_audit', schema=None) as batch_op:
        batch_op.create_index('idx_prompt_audit_challenge_id', ['challenge_id'], unique=False)
        batch_op.create_index('idx_prompt_audit_recorded_at', ['recorded_at'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenge_ids', sa.JSON(), nullable=True),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('completed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_started_at', ['started_at'], unique=False)
        batch_op.create_index('idx_sessions_user_id', ['user_id'], unique=False)

    op.create_table('streaks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=False),
    sa.Column('longest_record', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.create_index('idx_streaks_user_type', ['user_id', 'type'], unique=False)

    op.create_table('rounds',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('challenge_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('human_entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reveal_data', sa.JSON(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('completed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index('idx_rounds_challenge_id', ['challenge_id'], unique=False)
        batch_op.create_index('idx_rounds_session_id', ['session_id'], unique=False)
        batch_op.create_index('idx_rounds_state', ['state'], unique=False)

    op.create_table('entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('validity', sa.JSON(), nullable=True),
    sa.Column('constraint_violations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index('idx_entries_author_type', ['author_type'], unique=False)
        batch_op.create_index('idx_entries_round_id', ['round_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('time_bonus', sa.Integer(), nullable=False),
    sa.Column('streak_bonus', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('scored_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index('idx_scores_scored_at', ['scored_at'], unique=False)
        batch_op.create_index('idx_scores_user_id', ['user_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_entry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voted_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index('idx_votes_round_id', ['round_id'], unique=False)
        batch_op.create_index('idx_votes_user_id', ['user_id'], unique=False)

    op.create_table('ai_entries',
    sa.Column('entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sanitized_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('generated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('humanity_scores',
    sa.Column('entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('humanity_score', sa.Float(), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('last_updated', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    with op.batch_alter_table('humanity_scores', schema=None) as batch_op:
        batch_op.create_index('idx_humanity_scores_last_updated', ['last_updated'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('humanity_scores', schema=None) as batch_op:
        batch_op.drop_index('idx_humanity_scores_last_updated')

    op.drop_table('humanity_scores')
    op.drop_table('ai_entries')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index('idx_votes_user_id')
        batch_op.drop_index('idx_votes_round_id')

    op.drop_table('votes')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index('idx_scores_user_id')
        batch_op.drop_index('idx_scores_scored_at')

    op.drop_table('scores')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index('idx_entries_round_id')
        batch_op.drop_index('idx_entries_author_type')

    op.drop_table('entries')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index('idx_rounds_state')
        batch_op.drop_index('idx_rounds_session_id')
        batch_op.drop_index('idx_rounds_challenge_id')

    op.drop_table('rounds')
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.drop_index('idx_streaks_user_type')

    op.drop_table('streaks')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_user_id')
        batch_op.drop_index('idx_sessions_started_at')

    op.drop_table('sessions')
    with op.batch_alter_table('prompt_audit', schema=None) as batch_op:
        batch_op.drop_index('idx_prompt_audit_recorded_at')
        batch_op.drop_index('idx_prompt_audit_challenge_id')

    op.drop_table('prompt_audit')
    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_leaderboard_date')

    op.drop_table('leaderboard_snapshots')
    op.drop_table('challenge_daily')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_guest_id')
        batch_op.drop_index('idx_users_detection_rating')

    op.drop_table('users')
    op.drop_table('challenges')
    # ### end Alembic commands ###
